name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # Readme Profile
      - name: Achievements
        # if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes

      - name: General
        # if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: renaldyhidayatt
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Jakarta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 4
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_ignored: html, css
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: renaldyhidayatt
